### ISSUE TITLE
Why so much BengaliWordList version? All are same??

### ISSUE THREAD

**Issue by sarafinmahtab** [MinhasKamal/BengaliDictionary#2]
Please explain why there is multiple version in Bengali Word List and dictionary.

**Comment by MinhasKamal** [comment]
Each BengaliWordList version contains different number of words. Like this list- [BengaliWordList_40.rar](https://github.com/MinhasKamal/BengaliDictionary/raw/download/BengaliWordList_40.rar) contains most frequent 40k words.
