### ISSUE TITLE
How does this compare to avro's word list?

### ISSUE THREAD

**Issue by Oymate** [MinhasKamal/BengaliDictionary#5]
https://github.com/sarim/ibus-avro

**Comment by MinhasKamal** [comment]
Hello @Oymate ,

Can you please clarify your question a little? What type of comparison are you talking about?
Also, I did not find any word list in this repo: https://github.com/sarim/ibus-avro

**Comment by Oymate** [comment]
It's in the avrodict.js though it needs to be decoded

**Comment by MinhasKamal** [comment]
The file https://raw.githubusercontent.com/sarim/ibus-avro/master/avrodict.js contains Bengali word list. No meaning or description is added here only the word itself, similar to https://raw.githubusercontent.com/MinhasKamal/BengaliDictionary/master/BengaliWordList_48.txt

**Comment by Oymate** [comment]
So they are the same?

**Comment by MinhasKamal** [comment]
No, they are not the same, they are **similar**. You can work with either of them.
